server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopapp
    username: root
    password: ductrong1012
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretKey: yM6F9LdPOMN7eB8AqYTrpH5rcuC4NlUHoRUlwIRNbV8=

messages:
  basename: messages
  encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
